! -*- f90 -*------------------------------------------------------
! file: bed_functions.inc
! ----------------------------------------------------------------
! ----------------------------------------------------------------
! Battelle Memorial Institute
! Pacific Northwest Laboratory
! ----------------------------------------------------------------
! ----------------------------------------------------------------
! Created October 24, 2000 by William A. Perkins
! Last Change: Wed Feb 28 14:55:46 2001 by William A. Perkins <perk@dora.pnl.gov>
! ----------------------------------------------------------------

! RCS ID: $Id$ Battelle PNL

EXTERNAL bed_part_conc
EXTERNAL bed_part_vconc
EXTERNAL bed_pore_conc
EXTERNAL bed_porosity
EXTERNAL bed_depth
EXTERNAL bed_sediment_mass
EXTERNAL bed_max_erosion
EXTERNAL bed_max_part_erosion
DOUBLE PRECISION bed_part_conc
DOUBLE PRECISION bed_part_vconc
DOUBLE PRECISION bed_pore_conc
DOUBLE PRECISION bed_porosity
DOUBLE PRECISION bed_depth
DOUBLE PRECISION bed_sediment_mass
DOUBLE PRECISION bed_max_erosion
DOUBLE PRECISION bed_max_part_erosion
