#!MC 900
$!ALTERDATA 
  EQUATION = '{xm} = {x}*0.3048' 
$!ALTERDATA 
  EQUATION = '{ym} = {y}*0.3048' 
$!TWODAXIS XVAR = 18
$!TWODAXIS YVAR = 19
$!TWODAXIS XDETAIL{TITLE{TITLEMODE = USETEXT}}
$!TWODAXIS XDETAIL{TITLE{TEXT = 'x, m'}}
$!TWODAXIS YDETAIL{TITLE{TITLEMODE = USETEXT}}
$!TWODAXIS YDETAIL{TITLE{TEXT = 'y, m'}}
$!EXPORTSETUP 
  EXPORTFORMAT = EPS
  PRECISION = 3
  PALETTE = COLOR
  EPSPREVIEWIMAGE { IMAGETYPE = NONE }
$!EXPORT  
  APPEND = FALSE
