/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


void BuildDialog1(int  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;
  Dialog1Manager = GUI_DialogCreateModal(ParentDialog,
                                          5662,
                                          2147,
                                          "MASS2 Loader",
                                          Dialog1HelpButton_CB,
                                          Dialog1OkButton_CB,
                                          Dialog1CancelButton_CB,
                                          Dialog1Init_CB);
  VarList_MLST_D1 = GUI_ListAdd(Dialog1Manager,
                                134,
                                276,
                                5398,
                                786,
                       1,
                       VarList_MLST_D1_CB);
  VariablestoI_LBL_D1 = GUI_LabelAdd(Dialog1Manager,
                                     284,
                                     138,
                    "Variables to Include:");
  StartTimePla_LBL_D1 = GUI_LabelAdd(Dialog1Manager,
                                     239,
                                     1195,
                    "Start Time Plane: ");
  EndTimePlane_LBL_D1 = GUI_LabelAdd(Dialog1Manager,
                                     239,
                                     1705,
                    "End Time Plane: ");
  EndList_SLST_D1 = GUI_ListAdd(Dialog1Manager,
                                2332,
                                1654,
                                3259,
                                427,
                       0,
                       EndList_SLST_D1_CB);
  StartList_SLST_D1 = GUI_ListAdd(Dialog1Manager,
                                  2332,
                                  1145,
                                  3259,
                                  427,
                       0,
                       StartList_SLST_D1_CB);
}

void InitTGB(void)
{
/* Currently not used */
}
