/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUI.h"
#include "GUIDEFS.h"
int Dialog1Manager = BADDIALOGID;
int VarList_MLST_D1 = BADDIALOGID;
int VariablestoI_LBL_D1 = BADDIALOGID;
int StartTimePla_LBL_D1 = BADDIALOGID;
int EndTimePlane_LBL_D1 = BADDIALOGID;
int EndList_SLST_D1 = BADDIALOGID;
int StartList_SLST_D1 = BADDIALOGID;
