/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern int  Dialog1Manager;
extern void BuildDialog1(int  ParentDialog);

extern int  VarList_MLST_D1;
extern int  VariablestoI_LBL_D1;
extern int  StartTimePla_LBL_D1;
extern int  EndTimePlane_LBL_D1;
extern int  EndList_SLST_D1;
extern int  StartList_SLST_D1;
